### ISSUE TITLE
Can't Build For Deployment 

### ISSUE THREAD

**Issue by tonymarma** [arifintahu/dexplorer#6]
Hi, I've forked and tried to deploy on vercel, and it failed. I also tried on my local system 😕. 
After ```npm run build``` it gives many errors.

[23:34:11] Running build in Washington, D.C., USA (East) – iad1
[23:34:12] Cloning github.com/tonymarma/tester (Branch: main, Commit: 41ae46a)
[23:34:13] Previous build cache not available
[23:34:13] Cloning completed: 664.35ms
[23:34:13] Running "vercel build"
[23:34:14] Vercel CLI 33.5.1
[23:34:14] Installing dependencies...
[23:34:28] 
[23:34:28] > dexplorer@0.1.0 prepare
[23:34:28] > husky install
[23:34:28] 
[23:34:28] husky - Git hooks installed
[23:34:28] 
[23:34:28] added 567 packages in 14s
[23:34:28] 
[23:34:28] 143 packages are looking for funding
[23:34:28]   run `npm fund` for details
[23:34:28] Detected Next.js version: 13.2.4
[23:34:28] Detected `package-lock.json` generated by npm 7+
[23:34:28] Running "npm run build"
[23:34:37] 
[23:34:37] > dexplorer@0.1.0 build
[23:34:37] > next build
[23:34:37] 
[23:34:37] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[23:34:37] This information is used to shape Next.js' roadmap and prioritize features.
[23:34:37] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[23:34:37] https://nextjs.org/telemetry
[23:34:37] 
[23:34:37] info  - Linting and checking validity of types...
[23:34:50] info  - Creating an optimized production build...
[23:35:01] Browserslist: caniuse-lite is outdated. Please run:
[23:35:01]   npx browserslist@latest --update-db
[23:35:01]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[23:35:13] info  - Compiled successfully
[23:35:13] info  - Collecting page data...
[23:35:14] /!\ You are using legacy implementation. Please update your code: use createWrapper() and wrapper.useWrappedStore().
[23:35:14] /vercel/path0/node_modules/@namada/shared/dist/index.js:10
[23:35:14] import { deserialize } from "@dao-xyz/borsh";
[23:35:14] ^^^^^^
[23:35:14] 
[23:35:14] SyntaxError: Cannot use import statement outside a module
[23:35:14]     at internalCompileFunction (node:internal/vm:73:18)
[23:35:14]     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
[23:35:14]     at Module._compile (node:internal/modules/cjs/loader:1220:27)
[23:35:14]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[23:35:14]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[23:35:14]     at Module._load (node:internal/modules/cjs/loader:960:12)
[23:35:14]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[23:35:14]     at require (node:internal/modules/cjs/helpers:119:18)
[23:35:14]     at 9276 (/vercel/path0/.next/server/pages/index.js:273:18)
[23:35:14]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[23:35:14] 
[23:35:14] > Build error occurred
[23:35:14] Error: Failed to collect page data for /
[23:35:14]     at /vercel/path0/node_modules/next/dist/build/utils.js:1055:15
[23:35:14]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[23:35:14]   type: 'Error'
[23:35:14] }
[23:35:14] Error: Command "npm run build" exited with 1
[23:35:16]

**Comment by arifintahu** [comment]
Hi, currently Dexplorer doesn't support the Namada chain since Namada is not using the Cosmos SDK framework.
